Repository 7-final-project/reservation, pull requests merged in 2025-01, with the labels that each got.

#6 예약 CRUD 기능 구현
  build.gradle
  src/main/java/com/qring/reservation/application/global/exception/BadRequestException.java
  src/main/java/com/qring/reservation/application/global/exception/DuplicateResourceException.java
  src/main/java/com/qring/reservation/application/global/exception/EntityNotFoundException.java
  src/main/java/com/qring/reservation/application/global/exception/ErrorCode.java
  src/main/java/com/qring/reservation/application/global/exception/ReservationException.java
  src/main/java/com/qring/reservation/application/global/exception/UnauthorizedAccessException.java
  src/main/java/com/qring/reservation/application/global/handler/GlobalExceptionHandler.java
  src/main/java/com/qring/reservation/application/v1/message/KafkaMessageProducerV1.java
  src/main/java/com/qring/reservation/application/v1/res/ReservationGetByIdResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/res/ReservationPostResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/res/ReservationSearchResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/service/ReservationServiceV1.java
  src/main/java/com/qring/reservation/domain/model/ReservationEntity.java
  src/main/java/com/qring/reservation/domain/model/constraint/ReservationStatus.java
  src/main/java/com/qring/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/qring/reservation/infrastructure/auditing/AuditorAwareImpl.java
  src/main/java/com/qring/reservation/infrastructure/config/JpaConfig.java
  src/main/java/com/qring/reservation/infrastructure/config/QuerydslConfig.java
  src/main/java/com/qring/reservation/infrastructure/config/ReservationKafkaConfig.java
  src/main/java/com/qring/reservation/infrastructure/docs/ReservationControllerSwagger.java
  src/main/java/com/qring/reservation/infrastructure/messaging/KafkaMessageProducerImplV1.java
  src/main/java/com/qring/reservation/infrastructure/repository/JpaReservationRepository.java
  src/main/java/com/qring/reservation/infrastructure/repository/ReservationRepositoryImpl.java
  src/main/java/com/qring/reservation/infrastructure/util/PassportUtil.java
  src/main/java/com/qring/reservation/presentation/v1/controller/ReservationControllerV1.java
  src/main/java/com/qring/reservation/presentation/v1/req/PostReservationReqDTOV1.java
  src/main/resources/application-dev.yml
Labels: ✨ Feature, 🌐 API

#8 FeignClient 및 메시지 서비스 관련 로직 추가
  src/main/java/com/qring/reservation/application/v1/message/KafkaMessageProducerV1.java
  src/main/java/com/qring/reservation/application/v1/res/CouponTableGetByUserIdResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/res/ReservationGetByIdResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/res/ReservationPostResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/res/ReservationSearchResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/res/RestaurantGetByIdResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/res/RestaurantIdTableResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/service/ReservationServiceV1.java
  src/main/java/com/qring/reservation/domain/model/ReservationEntity.java
  src/main/java/com/qring/reservation/domain/model/constraint/ReservationStatus.java
  src/main/java/com/qring/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/qring/reservation/infrastructure/client/CouponClient.java
  src/main/java/com/qring/reservation/infrastructure/client/RestaurantClient.java
  src/main/java/com/qring/reservation/infrastructure/config/KafkaConsumerConfig.java
  src/main/java/com/qring/reservation/infrastructure/config/KafkaProducerConfig.java
  src/main/java/com/qring/reservation/infrastructure/messaging/KafkaMessageConsumerV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/KafkaMessageProducerImplV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/QueueAlarmEventDTOV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/ReservationCreateEventDTOV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/ReservationUpdateEventDTOV1.java
  src/main/java/com/qring/reservation/infrastructure/repository/JpaReservationRepository.java
  src/main/java/com/qring/reservation/infrastructure/repository/ReservationRepositoryImpl.java
  src/main/java/com/qring/reservation/presentation/v1/req/PostReservationReqDTOV1.java
  src/main/resources/application-dev.yml
Labels: ✨ Feature, 🔨 Refactor, 🌐 API

#9 AuthClient 추가
  src/main/java/com/qring/reservation/application/v1/message/KafkaMessageProducerV1.java
  src/main/java/com/qring/reservation/application/v1/res/UserGetByIdResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/service/ReservationServiceV1.java
  src/main/java/com/qring/reservation/infrastructure/client/AuthClient.java
  src/main/java/com/qring/reservation/infrastructure/messaging/KafkaMessageProducerImplV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/ReservationSendUserInfoEventDTOV1.java
Labels: ✨ Feature, 🌐 API

#14 application-prod.yml 수정 요구 사항 반영
  src/main/resources/application-prod.yml
Labels: ⚙ Setting, ✨ Feature, 🚀 Deploy

#16 yml 파일 수정 및 KafkaConfig 수정
  src/main/java/com/qring/reservation/infrastructure/config/KafkaConfig.java
  src/main/java/com/qring/reservation/infrastructure/config/KafkaConsumerConfig.java
  src/main/java/com/qring/reservation/infrastructure/config/KafkaProducerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: ⚙ Setting, 🔨 Refactor

#18 예약 서비스 코드 리팩토링
  src/main/java/com/qring/reservation/application/v1/message/KafkaMessageProducerV1.java
  src/main/java/com/qring/reservation/application/v1/res/CouponTableGetByUserIdResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/res/RestaurantGetByIdResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/res/RestaurantIdTableResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/res/UserGetByIdResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/service/ReservationServiceV1.java
  src/main/java/com/qring/reservation/domain/model/constraint/RoleType.java
  src/main/java/com/qring/reservation/infrastructure/messaging/KafkaMessageProducerImplV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/CreateReservationMessageDTOV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/ReservationCreateEventDTOV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/ReservationSendUserInfoEventDTOV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/ReservationUpdateEventDTOV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/SendUserInfoMessageDTOV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/UpdateReservationMessageDTOV1.java
  src/main/java/com/qring/reservation/presentation/v1/controller/ReservationControllerV1.java
Labels: 🔨 Refactor

#20 예약 서비스 리팩토링
  src/main/java/com/qring/reservation/application/v1/res/RestaurantGetByIdResDTOV1.java
  src/main/java/com/qring/reservation/application/v1/service/ReservationServiceV1.java
  src/main/java/com/qring/reservation/domain/repository/ReservationRepository.java
  src/main/java/com/qring/reservation/infrastructure/docs/ReservationControllerSwagger.java
  src/main/java/com/qring/reservation/infrastructure/messaging/KafkaMessageConsumerV1.java
  src/main/java/com/qring/reservation/infrastructure/messaging/dto/CreateReservationMessageDTOV1.java
  src/main/java/com/qring/reservation/infrastructure/repository/ReservationRepositoryImpl.java
  src/main/java/com/qring/reservation/presentation/v1/controller/ReservationControllerV1.java
  src/main/resources/application-dev.yml
Labels: 🔨 Refactor
